# coding: utf-8
#
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# 课程种类-小学
category = Category.create(:subject => "数学",:second => "小学",:third => "一年级")
category = Category.create(:subject => "语文",:second => "小学",:third => "一年级")
category = Category.create(:subject => "英语",:second => "小学",:third => "一年级")
category = Category.create(:subject => "作文",:second => "小学",:third => "一年级")
category = Category.create(:subject => "美术",:second => "小学",:third => "一年级")
category = Category.create(:subject => "音乐",:second => "小学",:third => "一年级")
category = Category.create(:subject => "数学",:second => "小学",:third => "二年级")
category = Category.create(:subject => "语文",:second => "小学",:third => "二年级")
category = Category.create(:subject => "英语",:second => "小学",:third => "二年级")
category = Category.create(:subject => "作文",:second => "小学",:third => "二年级")
category = Category.create(:subject => "美术",:second => "小学",:third => "二年级")
category = Category.create(:subject => "音乐",:second => "小学",:third => "二年级")
category = Category.create(:subject => "数学",:second => "小学",:third => "三年级")
category = Category.create(:subject => "语文",:second => "小学",:third => "三年级")
category = Category.create(:subject => "英语",:second => "小学",:third => "三年级")
category = Category.create(:subject => "作文",:second => "小学",:third => "三年级")
category = Category.create(:subject => "美术",:second => "小学",:third => "三年级")
category = Category.create(:subject => "音乐",:second => "小学",:third => "三年级")
category = Category.create(:subject => "数学",:second => "小学",:third => "四年级")
category = Category.create(:subject => "语文",:second => "小学",:third => "四年级")
category = Category.create(:subject => "英语",:second => "小学",:third => "四年级")
category = Category.create(:subject => "作文",:second => "小学",:third => "四年级")
category = Category.create(:subject => "美术",:second => "小学",:third => "四年级")
category = Category.create(:subject => "音乐",:second => "小学",:third => "四年级")
category = Category.create(:subject => "数学",:second => "小学",:third => "五年级")
category = Category.create(:subject => "语文",:second => "小学",:third => "五年级")
category = Category.create(:subject => "英语",:second => "小学",:third => "五年级")
category = Category.create(:subject => "作文",:second => "小学",:third => "五年级")
category = Category.create(:subject => "美术",:second => "小学",:third => "五年级")
category = Category.create(:subject => "音乐",:second => "小学",:third => "五年级")
category = Category.create(:subject => "数学",:second => "小学",:third => "六年级")
category = Category.create(:subject => "语文",:second => "小学",:third => "六年级")
category = Category.create(:subject => "英语",:second => "小学",:third => "六年级")
category = Category.create(:subject => "作文",:second => "小学",:third => "六年级")
category = Category.create(:subject => "美术",:second => "小学",:third => "六年级")
category = Category.create(:subject => "音乐",:second => "小学",:third => "六年级")
#课程种类-初中
category = Category.create(:subject => "数学",:second => "初中",:third => "一年级")
category = Category.create(:subject => "语文",:second => "初中",:third => "一年级")
category = Category.create(:subject => "英语",:second => "初中",:third => "一年级")
category = Category.create(:subject => "作文",:second => "初中",:third => "一年级")
category = Category.create(:subject => "物理",:second => "初中",:third => "一年级")
category = Category.create(:subject => "化学",:second => "初中",:third => "一年级")
category = Category.create(:subject => "政治",:second => "初中",:third => "一年级")
category = Category.create(:subject => "历史",:second => "初中",:third => "一年级")
category = Category.create(:subject => "理化",:second => "初中",:third => "一年级")
category = Category.create(:subject => "数学",:second => "初中",:third => "二年级")
category = Category.create(:subject => "语文",:second => "初中",:third => "二年级")
category = Category.create(:subject => "英语",:second => "初中",:third => "二年级")
category = Category.create(:subject => "作文",:second => "初中",:third => "二年级")
category = Category.create(:subject => "物理",:second => "初中",:third => "二年级")
category = Category.create(:subject => "化学",:second => "初中",:third => "二年级")
category = Category.create(:subject => "政治",:second => "初中",:third => "二年级")
category = Category.create(:subject => "历史",:second => "初中",:third => "二年级")
category = Category.create(:subject => "理化",:second => "初中",:third => "二年级")
category = Category.create(:subject => "数学",:second => "初中",:third => "三年级")
category = Category.create(:subject => "语文",:second => "初中",:third => "三年级")
category = Category.create(:subject => "英语",:second => "初中",:third => "三年级")
category = Category.create(:subject => "作文",:second => "初中",:third => "三年级")
category = Category.create(:subject => "物理",:second => "初中",:third => "三年级")
category = Category.create(:subject => "化学",:second => "初中",:third => "三年级")
category = Category.create(:subject => "政治",:second => "初中",:third => "三年级")
category = Category.create(:subject => "历史",:second => "初中",:third => "三年级")
category = Category.create(:subject => "理化",:second => "初中",:third => "三年级")
#课程种类-高中
category = Category.create(:subject => "数学",:second => "高中",:third => "一年级")
category = Category.create(:subject => "语文",:second => "高中",:third => "一年级")
category = Category.create(:subject => "英语",:second => "高中",:third => "一年级")
category = Category.create(:subject => "作文",:second => "高中",:third => "一年级")
category = Category.create(:subject => "物理",:second => "高中",:third => "一年级")
category = Category.create(:subject => "化学",:second => "高中",:third => "一年级")
category = Category.create(:subject => "政治",:second => "高中",:third => "一年级")
category = Category.create(:subject => "历史",:second => "高中",:third => "一年级")
category = Category.create(:subject => "地理",:second => "高中",:third => "一年级")
category = Category.create(:subject => "物理化",:second => "高中",:third => "一年级")
category = Category.create(:subject => "数学",:second => "高中",:third => "二年级")
category = Category.create(:subject => "语文",:second => "高中",:third => "二年级")
category = Category.create(:subject => "英语",:second => "高中",:third => "二年级")
category = Category.create(:subject => "作文",:second => "高中",:third => "二年级")
category = Category.create(:subject => "物理",:second => "高中",:third => "二年级")
category = Category.create(:subject => "化学",:second => "高中",:third => "二年级")
category = Category.create(:subject => "政治",:second => "高中",:third => "二年级")
category = Category.create(:subject => "历史",:second => "高中",:third => "二年级")
category = Category.create(:subject => "地理",:second => "高中",:third => "二年级")
category = Category.create(:subject => "物理化",:second => "高中",:third => "二年级")
category = Category.create(:subject => "数学",:second => "高中",:third => "三年级")
category = Category.create(:subject => "语文",:second => "高中",:third => "三年级")
category = Category.create(:subject => "英语",:second => "高中",:third => "三年级")
category = Category.create(:subject => "作文",:second => "高中",:third => "三年级")
category = Category.create(:subject => "物理",:second => "高中",:third => "三年级")
category = Category.create(:subject => "化学",:second => "高中",:third => "三年级")
category = Category.create(:subject => "政治",:second => "高中",:third => "三年级")
category = Category.create(:subject => "历史",:second => "高中",:third => "三年级")
category = Category.create(:subject => "地理",:second => "高中",:third => "三年级")
category = Category.create(:subject => "物理化",:second => "高中",:third => "三年级")
#课程种类-其他
category = Category.create(:subject => "音乐艺考",:second => "其他",:third => "音乐")
category = Category.create(:subject => "钢管",:second => "其他",:third => "音乐")
category = Category.create(:subject => "吉他",:second => "其他",:third => "音乐")
category = Category.create(:subject => "古琴",:second => "其他",:third => "音乐")
category = Category.create(:subject => "架子鼓",:second => "其他",:third => "音乐")
category = Category.create(:subject => "黑管",:second => "其他",:third => "音乐")
category = Category.create(:subject => "长笛",:second => "其他",:third => "音乐")
category = Category.create(:subject => "芭蕾",:second => "其他",:third => "舞蹈")
category = Category.create(:subject => "民族",:second => "其他",:third => "舞蹈")
category = Category.create(:subject => "街舞",:second => "其他",:third => "舞蹈")
category = Category.create(:subject => "美术艺考",:second => "其他",:third => "美术")
category = Category.create(:subject => "素描",:second => "其他",:third => "美术")
category = Category.create(:subject => "水彩",:second => "其他",:third => "美术")
category = Category.create(:subject => "油画",:second => "其他",:third => "美术")
category = Category.create(:subject => "速写",:second => "其他",:third => "美术")
category = Category.create(:subject => "摄影",:second => "其他",:third => "美术")
category = Category.create(:subject => "书法",:second => "其他",:third => "美术")
category = Category.create(:subject => "羽毛球",:second => "其他",:third => "体育")
category = Category.create(:subject => "足球",:second => "其他",:third => "体育")
category = Category.create(:subject => "乒乓球",:second => "其他",:third => "体育")
category = Category.create(:subject => "篮球",:second => "其他",:third => "体育")
category = Category.create(:subject => "排球",:second => "其他",:third => "体育")
category = Category.create(:subject => "游泳",:second => "其他",:third => "体育")
category = Category.create(:subject => "太极",:second => "其他",:third => "体育")
category = Category.create(:subject => "跆拳道",:second => "其他",:third => "体育")

#job
infoCategory=InfoCategory.create(:title=>"学生兼职")
infoCategory=InfoCategory.create(:title=>"模特")
infoCategory=InfoCategory.create(:title=>"礼仪小姐") 
infoCategory=InfoCategory.create(:title=>"摄影师") 
infoCategory=InfoCategory.create(:title=>"小时工/钟点工") 
infoCategory=InfoCategory.create(:title=>"促销员") 
infoCategory=InfoCategory.create(:title=>"传单派发") 
infoCategory=InfoCategory.create(:title=>"问卷调查") 
infoCategory=InfoCategory.create(:title=>"手工制作") 
infoCategory=InfoCategory.create(:title=>"网站建设") 
infoCategory=InfoCategory.create(:title=>"设计制作") 
infoCategory=InfoCategory.create(:title=>"家教") 
infoCategory=InfoCategory.create(:title=>"会计") 
infoCategory=InfoCategory.create(:title=>"翻译") 
infoCategory=InfoCategory.create(:title=>"实习生") 
infoCategory=InfoCategory.create(:title=>"酒吧KTV") 
infoCategory=InfoCategory.create(:title=>"服务员") 
infoCategory=InfoCategory.create(:title=>"销售") 
infoCategory=InfoCategory.create(:title=>"其他兼职")
